# Generated by Django 5.0.3 on 2024-05-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile_old_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothingSize',
        ),
    ]
