# Generated by Django 5.0.3 on 2024-05-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_shipped_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
